CREATE DATABASE WEBSITE;

USE DATABASE WEBSITE;

CREATE TABLE USER_WS (
    ID_USER INTEGER NOT NULL IDENTITY(1,1),
    USERNAME VARCHAR(50) NOT NULL,
    USER_PASS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TYPE_USER VARCHAR(3) NOT NULL,
    CREATION_DATE DATETIME NOT NULL,
    PRIMARY KEY (ID_USER)
);

CREATE TABLE PRODUCT (
    CODIGO_PROD VARCHAR(100) NOT NULL,
    TIPO_PROD VARCHAR(100) NOT NULL,
    PRECIO_UNIT NUMERIC NOT NULL,
	PRIMARY KEY(CODIGO_PROD)
);

CREATE TABLE ORDEN_COMPRA (
    NUM_PEDIDO INTEGER NOT NULL IDENTITY(1,1),
    FECHA_COMPRA DATETIME NOT NULL,
    ID_USER INTEGER NOT NULL,
    PRODUCT VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    MONTO_TOTAL NUMERIC NOT NULL,
    PRIMARY KEY (NUM_PEDIDO)
);

ALTER TABLE ORDEN_COMPRA ADD FOREIGN KEY (ID_USER) REFERENCES USER_WS(ID_USER);
ALTER TABLE ORDEN_COMPRA ADD FOREIGN KEY (PRODUCT) REFERENCES PRODUCT(CODIGO_PROD);

INSERT INTO PRODUCT (CODIGO_PROD, TIPO_PROD, PRECIO_UNIT)
VALUES ('PROD-32545', 'BEBIDA', '1000')

INSERT INTO PRODUCT (CODIGO_PROD, TIPO_PROD, PRECIO_UNIT)
VALUES ('PROD-89759', 'GALLETA', '700')